### ISSUE TITLE
Go support

### ISSUE THREAD

**Issue by munnik** [asimmon/bomberjam-contest#10]
Nice project! I would like to give it a try with a bot written in [Go](https://golang.org/). I think Go is quite a popular language for AI and it would be nice to see support for it on this project.

**Comment by asimmon** [comment]
Thanks! I've learned the basics of Go yesterday and I should be able to add Go support on the backend and publish a Go starter kit later today.

**Comment by asimmon** [comment]
There you go! The "startert kits" download link has been updated.

![image](https://user-images.githubusercontent.com/14242083/116010785-48ad0f00-a5ef-11eb-873e-c24531d90fd2.png)

The biggest challenge was to ensure that the source files and any `go.mod` dependencies were packaged together during the compilation process because that's the only moment where you can have access to internet, and that without permissions issues.
